apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-nextjs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-nextjs-app
  template:
    metadata:
      labels:
        app: your-nextjs-app
    spec:
      containers:
      - name: your-nextjs-container
        image: subh12/advancenextjs13-app:v1
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGODB_URL
        - name: CLERK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLERK_SECRET_KEY
        - name: NEXT_CLERK_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_CLERK_WEBHOOK_SECRET
        - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        - name: NEXT_PUBLIC_CLERK_SIGN_UP_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        - name: NEXT_PUBLIC_TINY_EDITOR_API_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NEXT_PUBLIC_TINY_EDITOR_API_KEY
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
