apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MONGODB_URL: bW9uZ29kYitzcnY6Ly9yYW1ibGVycmFuYTQ3OlJhbmExMjM0QGNsdXN0ZXIwLmlsa2xueWUubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  CLERK_SECRET_KEY: c2tfdGVzdF9Tc3NMTHFwSzFzQlYxQ09GV2xzUmF0RWNKUUpjSkNwcmM1SllLblJ0eWE=
  NEXT_CLERK_WEBHOOK_SECRET: d2hzZWNfUk5OclQvc2VNamtHTU14M2RYaVBTbVNsVC9CeG43bEUK
