apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  labels:
    app: your-nextjs-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: your-nextjs-app
